# For more info on HTTP files go to https://aka.ms/vs/httpfile


GET http://localhost:5050/api/plants

###

GET http://localhost:5050/api/plants/3

###

POST http://localhost:5050/api/plants
Content-Type: application/json

{
    "name": "Mini Cucumber",
    "type": "Cucumber",
    "wateringIntervalDays": 2,
    "lastWateredDate": "2026-04-03",
    "sunExposure": "Full Sun",
    "notes": "Train vines vertically to save space and improve air circulation."
}

###

PUT http://localhost:5050/api/plants/4
Content-Type: application/json

{
  "name": "Mini Big Cucumber",
  "type": "Cucumber",
  "wateringIntervalDays": 2,
  "lastWateredDate": "2026-04-03",
  "sunExposure": "Full Sun",
  "notes": "Train vines vertically to save space and improve air circulation."
}

###

DELETE http://localhost:5050/api/plants/4

###

PATCH http://localhost:5050/api/plants/3/water 