# For more info on HTTP files go to https://aka.ms/vs/httpfile


GET http://localhost:5050/api/plants

###

GET http://localhost:5050/api/plants/3

###

POST http://localhost:5050/api/plants
Content-Type: application/json

{
    "name": "2",
    "typeId": 2,
    "wateringIntervalDays": 42,
    "notes": "Train vines vertically to save space and improve air circulation."
}

###

PUT http://localhost:5050/api/plants/3
Content-Type: application/json

{
  "name": "Mini Cucumber",
  "typeId": 3,
  "wateringIntervalDays": 2,
  "lastWateredDate": "2024-04-03",
  "notes": "Train vines vertically to save space and improve air circulation."
}

###

DELETE http://localhost:5050/api/plants/1

###

PATCH http://localhost:5050/api/plants/3/water 